export interface Calendar{
    name: string,
    days: Days[]
}

export interface Days{
    day: number,
    anxiety: string,
    daily: string,
    exercise: string,
    health: string,
    hobby: string,
    sexual: string,
    sleep: string,
    work: string
}

export class CalendarDefaultValue{
    defaultValue: Calendar[] = [
        {
          name: 'January.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'February.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'March.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ],
          
        },
        {
          name: 'April.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]   
        },
        {
          name: 'May.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'June.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'July.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'August.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'September.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'October.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'November.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
        {
          name: 'December.',
          days: [
            { day: 1, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 2, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 3, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 4, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 5, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 6, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 7, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 8, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 9, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 10, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 11, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 12, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 13, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 14, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 15, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 16, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 17, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 18, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 19, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 20, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 21, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 22, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 23, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 24, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 25, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 26, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 27, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 28, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 29, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 30, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' },
            { day: 31, anxiety: '0', daily: '0', exercise: '0', health: '0', hobby: '0', sexual: '0', sleep: '0', work: '0' }
          ]
        },
      ];
}